---
version: "3.4"
services:
  swarm-stack-nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /tmp:/usr/share/nginx/html
    deploy:
      mode: replicated
      replicas: 2
    healthcheck:
      test: ls
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
      